import type { Metadata } from "next";
import { Space_Mono, Work_Sans } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const space = Space_Mono({
    weight: "400",
    subsets: ['latin'],
    display: "swap"
});

const work = Work_Sans({
    weight: "400",
    subsets: ['latin'],
    display: "swap"
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${work.className} ${space.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
